### ISSUE TITLE
test.sh failed on MacOS and Linux (amd64)

### ISSUE THREAD

**Issue by v1v** [elastic/go-sysinfo#109]
The `github actions` for macos failed with the below error:

```
Run .ci/scripts/test.sh
+ GO111MODULE=off
+ go get -u github.com/elastic/go-licenser
+ go mod verify
all modules verified
+ go-licenser -d
+ go run .ci/scripts/check_format.go
Run goimports on the code.
providers/aix/boottime_test.go
providers/aix/defs_aix.go
providers/darwin/arch_darwin.go
providers/darwin/boottime_darwin.go
providers/darwin/defs_darwin.go
providers/darwin/host_darwin.go
providers/darwin/kernel_darwin.go
providers/darwin/machineid_darwin.go
providers/darwin/memory_darwin.go
providers/darwin/process_darwin.go
providers/darwin/process_darwin_test.go
providers/darwin/syscall_darwin.go
providers/linux/os_test.go
exit status 1
```

**Comment by v1v** [comment]
It also failed in Linux amd64

<img width="989" alt="image" src="https://user-images.githubusercontent.com/2871786/169809744-7df5c757-4bc9-47f2-9783-ef3255b931c1.png">

**Comment by andrewkroh** [comment]
Shouldn't the script be using `go install <pkg>@latest` instead of `go get`?

https://go.dev/doc/go-get-install-deprecation

**Comment by v1v** [comment]
Thanks @andrewkroh, those failures are happening with go `1.12.17`, I don't know what's the Golang version support for this project. But the existing support matrix is defined in https://github.com/elastic/go-sysinfo/blob/8b16752c173d0b1699232c8ecc54f814bcda4912/.ci/Jenkinsfile#L39-L42

As it was the version defined in `travis-ci`: https://github.com/elastic/go-sysinfo/pull/84/files

Other than that, who can help with this issue?

**Comment by fearful-symmetry** [comment]
Can we reproduce this error locally? I'm assuming there's some config or module issue that's making `go get` unhappy, particularly if it's happening with something older like `1.12`.

**Comment by andrewkroh** [comment]
I haven't looked at the problem, but wanted to mention that the project does not need to support Go 1.12. From my POV the requirement is to support the Go version used by Beats 7.17.

**Comment by v1v** [comment]
> Can we reproduce this error locally? I'm assuming there's some config or module issue that's making go get unhappy, particularly if it's happening with something older like 1.12.

No clue, I just reported the error that happens in two different CI ecosystems (GitHub actions and JenkinsCI). It worked in the past in the CI, but recent commits started to fail.

but let me give a go, as it requires to run `.ci/scripts/test.sh` within a go 1.12.17 version:

1) https://github.com/andrewkroh/gvm#installation
2) then run `.ci/scripts/test.sh`

it fails also locally

<img width="538" alt="image" src="https://user-images.githubusercontent.com/2871786/170216669-1c75bf3b-b332-4d85-947c-b1914e0fab67.png">
