### ISSUE TITLE
LoadAverage() Where is this used?

### ISSUE THREAD

**Issue by prologic** [elastic/go-sysinfo#120]
I'm looking at using your library to provide cross-platform (Linux, BSD and Darwin) System Information, but going through the docs and codebase I don't see where `.LoadAverage()` is ever used or the interface.

Is this just missing?

**Comment by amuttsch** [comment]
When will this be implemented? I could use it in my project. Thanks!

**Comment by prologic** [comment]
I guess someone needs to put up a PR 👌

**Comment by ariasmn** [comment]
So I would like to give it a try!

@andrewkroh any info about the status? Saw the reference in your other repository about merging both projects into a single one so maybe this is a bit pointless to work on?

**Comment by andrewkroh** [comment]
There no one slated to work on that merging of features from elastic-agent-system-metrics currently. So I recommend opening a PR to expedite this. Thanks.

**Comment by prologic** [comment]
Code looks good to me 👌 I can help test the Darwin version? 🤔

**Comment by ariasmn** [comment]
@prologic My main problem is on how to code it without testing while doing so :sweat: 

Should I just make the PR with the Linux changes and wait for someone else to open one for the `darwin` provider? Let's see what Andrew tells us!

**Comment by prologic** [comment]
What about you mock the expected data sources you expect to use/open/read on Darwin? 😅

**Comment by ariasmn** [comment]
> What about you mock the expected data sources you expect to use/open/read on Darwin? sweat_smile

I can, but as far as I know, Darwin does not have the `/proc/loadavg` file, and needs to use `sysctl vm.loadavg` instead. I think the output is way different from Linux, so I can't mock something that I don't know how it should be mocked.

Anyway, I'm setting up a VM so I will get to work on it ASAP, no worries.

**Comment by prologic** [comment]
But you can define an interface that is common and implement the interface right?
