### ISSUE TITLE
openEuler: osFamily value is null

### ISSUE THREAD

**Issue by pc-gh** [elastic/go-sysinfo#142]
when i use the code to get the value of os information.
```
h, err := sysinfo.Host()
info := h.Info()
fmt.Println(info.OS.Family)
```
osName show the value is "openEuler",but the info.OS.Family show the null value.

**Comment by andrewkroh** [comment]
It should given an empty string (not nil) when the Family is unknown for that OS. There's a small table of mappings in the code. To get it recognized you can contribute to that table for "openEuler" and add a test case
