### ISSUE TITLE
TestProcesses failing on CI for darwin

### ISSUE THREAD

**Issue by AndersonQ** [elastic/go-sysinfo#148]
The `TestProcesses` is constantly [failing on CI](https://beats-ci.elastic.co/blue/organizations/jenkins/Library%2Fgo-sysinfo-mbp/detail/PR-144/34/pipeline/152) at least for https://github.com/elastic/go-sysinfo/pull/144, but it seems to be happening on other PRs as well, even though it passes locally.

I don´t have a mac to investigate it further, I just got someone else to try it and as I said, itś working locally.

```
[2023-01-23T13:49:10.877Z] === RUN   TestProcesses

[2023-01-23T13:49:10.877Z]     process_darwin_test.go:115: empty exec

[2023-01-23T13:49:10.877Z] --- FAIL: TestProcesses (0.00s)

[2023-01-23T13:49:10.877Z] FAIL

[2023-01-23T13:49:10.877Z] FAIL	github.com/elastic/go-sysinfo/providers/darwin	0.671s
```

**Comment by andrewkroh** [comment]
This test looks non-deterministic in that it lists all processes and assumes the first one has an executable associated to it. If macos is like Linux and Windows, then this is not always true for special kernel processes.

https://github.com/elastic/go-sysinfo/blob/53d6396b5c22f10fa1fa4229525fa0cdb86a521f/providers/darwin/process_darwin_test.go#L98-L108

**Comment by andrewkroh** [comment]
I think we should update the test's error message to include the full process details so we can see what process is causing this.
