### ISSUE TITLE
AIX unimplemented error

### ISSUE THREAD

**Issue by serak** [elastic/go-sysinfo#162]
```
{"log.level":"info","@timestamp":"2023-04-06T16:23:44.996+0300","log.origin":{"file.name":"instance/beat.go","file.line":785},"message":"Home path: [/FBE/filebeat-aix] Config path: [/FBE/filebeat-aix] Data path: [/FBE/filebeat-aix/data] Logs path: [/FBE/filebeat-aix/logs]","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-04-06T16:23:44.996+0300","log.logger":"beat","log.origin":{"file.name":"instance/beat.go","file.line":859},"message":"Beat metadata path: /FBE/filebeat-aix/data/meta.json","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-04-06T16:23:44.996+0300","log.origin":{"file.name":"instance/beat.go","file.line":793},"message":"Beat ID: 33bf430e-c802-48f3-8800-a199572b6741","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-04-06T16:23:44.996+0300","log.origin":{"file.name":"instance/beat.go","file.line":1263},"message":"Exiting: failed to get host information: unimplemented","service.name":"filebeat","ecs.version":"1.6.0"}
Exiting: failed to get host information: unimplemented
```
How do i know which part is unimplemented ,FYI i am new to golang, but can scramble the internet to contribute to working code, my assumption is its this code, but could  not correlated with other os like linux to find what is missing in aix
```

func Host() (types.Host, error) {
	provider := registry.GetHostProvider()
	if provider == nil {
		return nil, types.ErrNotImplemented
	}
	return provider.Host()
}
```

**Comment by andrewkroh** [comment]
For AIX the `Host()` function is implemented at

https://github.com/elastic/go-sysinfo/blob/d4436c20660b7912c38f2cfa9d74422d009c3f98/providers/aix/host_aix_ppc64.go#L54-L57

in order for this to be included in your build, you must be targeting aix/ppc64 and have CGO enabled as per the build tag.

https://github.com/elastic/go-sysinfo/blob/d4436c20660b7912c38f2cfa9d74422d009c3f98/providers/aix/host_aix_ppc64.go#L18

So when you build the binary you need to ensure that you are using some variant of

`GOOS=aix GOARCH=ppc64 CGO_ENABLED=1 go build`
