### ISSUE TITLE
Swallowing errors

### ISSUE THREAD

**Issue by axw** [elastic/go-sysinfo#17]
Neither `types.CPUTimer.CPUTime()` nor `types.Memory.Memory()` return an error, so the implementations swallow errors. This means the caller must check the value if they want to be sure they're operating on valid information. Can we surface the error, and let the caller decide what to do with it?

**Comment by ruflin** [comment]
+1 on returning errors. @andrewkroh any thoughts?

**Comment by andrewkroh** [comment]
I know there are quite a few inconsistencies in this project at the moment and I'm really happy to have help getting them cleaned up.

+1
