### ISSUE TITLE
Unified CPUTimer interface for Host and Process?

### ISSUE THREAD

**Issue by axw** [elastic/go-sysinfo#18]
The Host and Process (by way of CPUTimer) interfaces currently have incompatible CPUTime methods:

```go
type Host interface {
    CPUTime() (*types.CPUTimes, error)
}

type CPUTimer interface {
    CPUTime() types.CPUTimes
}
```

It would be nice if they were the same. That would make it straightforward to implement functions that operate on a CPUTimer and accept either a Host or Process. By taking Host's current signature, we would also address https://github.com/elastic/go-sysinfo/issues/17 for the CPUTimer case.

**Comment by axw** [comment]
Slight aside, but if changing the CPUTimer interface, I'd suggest making it a non-pointer return so that the result is provably immutable.

**Comment by andrewkroh** [comment]
SGTM 👍

**Comment by ruflin** [comment]
+1
