### ISSUE TITLE
Use GOARCH for host architecture?

### ISSUE THREAD

**Issue by axw** [elastic/go-sysinfo#21]
At the moment, each of the OS providers is using OS-specific code to determine the architecture. Is there a  reason for doing this, rather than using the compiled-in GOARCH value?

**Comment by andrewkroh** [comment]
On multi-arch systems like x86_64 the runtime.GOARCH value doesn't definitively tell you what the system architecture is. Does that make sense? Or is there another option?

**Comment by axw** [comment]
Ah, I see, this is by design reporting AMD vs. Intel, etc. Fair enough, GOARCH is not suitable and there's no other alternative.

**Comment by axw** [comment]
... I think I missed the point

> On multi-arch systems like ...

(still GOARCH isn't useful, since it just tells you what arch the program was compiled for.)
