### ISSUE TITLE
Implement Host UniqueID on Darwin (macOS)

### ISSUE THREAD

**Issue by andrewkroh** [elastic/go-sysinfo#29]
The darwin provider implementation does not populate the [host UniqueID field](https://github.com/elastic/go-sysinfo/blob/7b021494a9562d0c3f0422d49b9980709c5650e9/types/host.go#L39).

Let's see if we can a Hardward UUID in a programatic manner.

- https://stackoverflow.com/questions/933460/unique-hardware-id-in-mac-os-x

**Comment by cwurm** [comment]
Implemented in https://github.com/elastic/go-sysinfo/pull/31.
