### ISSUE TITLE
BootTime for Windows inconsistent

### ISSUE THREAD

**Issue by Goggin** [elastic/go-sysinfo#53]
[BootTime for windows](https://github.com/elastic/go-sysinfo/blob/master/providers/windows/boottime_windows.go) is inconsistent and triggers constant [reboot notifications in AuditBeats](https://github.com/elastic/beats/blob/e007c9c9c1d423d1b7905e045aaa60c1f7ce572e/x-pack/auditbeat/module/system/host/host.go#L268) on Windows.

Example seen here:

<img width="527" alt="boottime inconsistencies" src="https://user-images.githubusercontent.com/6035439/57710149-59e6f600-763a-11e9-9936-5fe0fa7bc5ee.png">

**Comment by andrewkroh** [comment]
I think it would probably work if we truncated the boot time down do the second rather than the 10s of milliseconds.
