### ISSUE TITLE
Can't Install on MacOs Cataline

### ISSUE THREAD

**Issue by xfoxawy** [elastic/go-sysinfo#89]
Installing `github.com/elastic/go-sysinfo` on MacOs Catalone has this issue ,
```
github.com/elastic/go-sysinfo/providers/darwin
# github.com/elastic/go-sysinfo/providers/darwin
ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libproc.tbd' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by andresrc** [comment]
Thank you very much for creating this issue. However, we would kindly like to ask you to post all questions and issues on the [Discuss forum](https://discuss.elastic.co/c/beats) first. In addition to awesome, knowledgeable community contributors, core Beats developers are on the forums every single day to help you out as well. So, your questions will reach a wider audience there, and if we confirm that there is a bug, then you can reopen this issue with the new information or open a new one.
