### ISSUE TITLE
ProcessInfo is nil when env key is missing a value

### ISSUE THREAD

**Issue by wardn** [elastic/go-sysinfo#93]
The parser for darwin envronment variables throws an error if a key doesn't have a value due to "len(parts) != 2".  The error causes an empty types.ProcessInfo to get returned.

see https://github.com/elastic/go-sysinfo/pull/94

**Comment by andresrc** [comment]
@elastic/agent

**Comment by andresrc** [comment]
@fearful-symmetry can you take a look at this one? Thanks!
